### ISSUE TITLE
Set naming standard for meeting minute file names

### ISSUE THREAD

**Issue by funnelfiasco** [openpubkey/community#2]
Before we get too many files in the repo, we should standardize file names to be of the format `<YYYY>-<MM>-<DD>-<NAME>.md` (e.g. `2023-11-15-community.md` or `2023-12-06-tsc.md`).

This allows files to be more easily sorted/searched based on date, which will become more important the longer the project goes on.

Adding the name allows us to easily change the organization later without having to worry about name collisions (e.g. if we later decide to put all meeting minutes into a  single `meetings/` directory)

**Comment by asamborski** [comment]
Agreed. Thanks for the suggestion!

**Comment by asamborski** [comment]
Hey @funnelfiasco , we've implemented this change for both our tsc and community meeting minutes. I'm going to close this issue out with resounding success!
