### ISSUE TITLE
Create a TSC label in this repo

### ISSUE THREAD

**Issue by funnelfiasco** [openpubkey/community#4]
Let's create a "Technical Steering Committee" label in this repo that would allow us to tag things that the TSC needs to discuss/approve/etc.

**Comment by asamborski** [comment]
This sounds like a great idea. Do you have a label in mind? Maybe just TSC would suffice.

**Comment by funnelfiasco** [comment]
"TSC" is fine. I have a weak preference for "Technical Steering Committee" to reduce the use of acronyms/initialisms that people might not be familiar with, but "TSC" is used broadly enough that it should be okay. We'll want to document what it's for either way, and we can always change it if we find it causes confusion.

**Comment by asamborski** [comment]
Per TSC meeting yesterday, 2024-02-07, TSC it is!
